In [1]:
import numpy as np               # NumPyのみをインポート

def create_matrix(x):
    '''
        データx1、x2にバイアスに対応するx0(=1)を加えた行列を作成
    '''
    x0 = np.ones([x.shape[0], 1]) # バイアスに対応する1の項
    return np.hstack([x0, x])     # x0,x1,x2の行列を返す

def sigmoid(X, parameter):
    '''
        シグモイド関数
        ------------
        X         : x0、x1、x2の行列
        parameter : w0,w1,w3のベクトル
    '''
    return 1 / (1 + np.exp(-np.dot(X, parameter)))

def logistic_regression(X, t):
    '''
        二値分類の学習を行うパーセプトロン
        ------------
        X : x0、x1、x2の行列
        t : 正解ラベル
    '''
    LNR = 1e-1                    # 学習率を0.1に設定
    loop = 50                    # 更新回数
    count = 1                     # 処理回数をカウントする変数
    parameter = np.random.rand(3) # w0,w1,w2を初期化

    for i in range(loop):         # 学習をloop回繰り返す
        # w0,w1,w2の更新
        parameter = parameter - LNR*np.dot(
            sigmoid(X,parameter) - t,
            X
            )
        # 最初の1回と以降10回ごとにパラメーターの値を出力
        if (count == 1 or count % 10 == 0):
            print('{}回: parameter = {}'.format(count, parameter))        
        count += 1               # カウンター変数の値を1増やす
        
    return parameter             # 学習後のw0、w1、w2を返す

In [2]:
# ANDゲート
# x1、x2を行列xに代入
x =np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# 正解値をtに代入
t = np.array([0, 0, 0, 1])
# xにバイアス対応の1の項を追加して行列を作成
X = create_matrix(x)   
# パラメーターの値を学習する
parameter = logistic_regression(X, t)

1回: parameter = [0.06790247 0.23203932 0.89282791]
10回: parameter = [-0.86717022  0.17888753  0.70893195]
20回: parameter = [-1.3193361   0.39327394  0.81388821]
30回: parameter = [-1.62528265  0.63514461  0.97325745]
40回: parameter = [-1.88361823  0.8579253   1.13157548]
50回: parameter = [-2.11660495  1.05735135  1.28003308]


In [3]:
# 学習した重み・バイアスを使ってANDゲートを出力してみる
# sigmoid()の戻り値が0.5以上であれば1、そうでなければ0を返す
(sigmoid(
    create_matrix(
        np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
        ),
    parameter  # 学習後の重み・バイアス
) >= 0.5).astype(np.int)

array([0, 0, 0, 1])

In [4]:
# NANDゲート
# x1、x2を行列xに代入
x =np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# 正解値をtに代入
t = np.array([1, 1, 1, 0])
# xにバイアス対応の1の項を追加して行列を作成
X = create_matrix(x)
    
# パラメーターの値を学習する
parameter = logistic_regression(X, t)

1回: parameter = [ 0.58853327  0.37140645 -0.01804037]
10回: parameter = [ 0.8594955   0.01638414 -0.3027499 ]
20回: parameter = [ 1.1718506  -0.29903889 -0.55464716]
30回: parameter = [ 1.46341092 -0.56378488 -0.76917456]
40回: parameter = [ 1.72999679 -0.79291271 -0.95869248]
50回: parameter = [ 1.97410697 -0.99492377 -1.12939294]


In [5]:
# 学習した重み・バイアスを使ってANDゲートを出力してみる
# sigmoid()の戻り値が0.5以上であれば1、そうでなければ0を返す
(sigmoid(
    create_matrix(
        np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
        ),
    parameter  # 学習後の重み・バイアス
) >= 0.5).astype(np.int)

array([1, 1, 1, 0])

In [6]:
# ORゲート
# x1、x2を行列xに代入
x =np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# 正解値をtに代入
t = np.array([0, 1, 1, 1])
# xにバイアス対応の1の項を追加して行列を作成
X = create_matrix(x)
    
# パラメーターの値を学習する
parameter = logistic_regression(X, t)

1回: parameter = [0.87758304 0.55169863 0.84383626]
10回: parameter = [0.64856286 0.8009569  1.05778802]
20回: parameter = [0.42532359 1.05678945 1.27954919]
30回: parameter = [0.23137625 1.29273558 1.48633054]
40回: parameter = [0.06212118 1.51084185 1.67959184]
50回: parameter = [-0.08679028  1.71298524  1.8606183 ]


In [7]:
# 学習した重み・バイアスを使ってANDゲートを出力してみる
# sigmoid()の戻り値が0.5以上であれば1、そうでなければ0を返す
(sigmoid(
    create_matrix(
        np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
        ),
    parameter  # 学習後の重み・バイアス
) >= 0.5).astype(np.int)

array([0, 1, 1, 1])